name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  node:
    name: React Application Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setting up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      
      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # TODO: debug the lock-file not found issue
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="test"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
       
      - run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Linting
        run: pnpm exec nx affected -t lint --exclude='tag:rust-app' --configuration=production
      - name: Build
        run: pnpm exec nx affected -t build --exclude='tag:rust-app' --configuration=production
      - name: Testing
        run: pnpm exec nx affected -t test --exclude='tag:rust-app' --configuration=production

  rust:
    name: Rust Application Tasks
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setting up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
       
      - run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
      
      - name: Build
        run: pnpm exec nx affected -t build --exclude='tag:react-app' --configuration=production
      
      - name: Test
        run: pnpm exec nx affected -t test --exclude='tag:react-app' --configuration=production